### ISSUE TITLE
scubainit ignores SIGPIPE

### ISSUE THREAD

**Issue by haboustak** [JonathonReinhart/scuba#254]
The new `scubainit` included in version 2.13.0 ignores `SIGPIPE`, which is then inherited by any process that scuba runs. This behavior is included as a side-effect of the Rust entrypoint. See [rust-lang/rust #62569](https://github.com/rust-lang/rust/issues/62569)

Here's a test case that was shared with me recently and demonstrates the behavior change from `2.12.0` to `2.13.0`:
```
$ scuba --image debian:12 sh -c "yes | echo abcd"
abcd
yes: standard output: Broken pipe
```

Also, to show that `SIGPIPE` is ignored in `2.13.0`:
```
$ scuba --image debian:12 cat /proc/1/status | grep "Sig"
SigQ:	1/31475
SigPnd:	0000000000000000
SigBlk:	0000000000000000
SigIgn:	0000000000001000
SigCgt:	0000000000010002
```

I think the correct behavior for scuba is to reset `SIGPIPE` to `SIG_DFL`.

**Comment by JonathonReinhart** [comment]
I believe this is handled by #253, but I haven't looked at it yet.

**Comment by haboustak** [comment]
Ah yes. I came here looking for an issue and not a PR. I’d imagine the compiler flag will fix it.

**Comment by JonathonReinhart** [comment]
If I understand the problem statement correctly:
- The default disposition of `SIGPIPE` is Term: [signal(7)](https://man7.org/linux/man-pages/man7/signal.7.html#:~:text=SIGPIPE%20%20%20%20%20%20P1990%20%20%20%20%20%20Term)
- From [pipe(7)](https://man7.org/linux/man-pages/man7/pipe.7.html#:~:text=If%20all%20file%20descriptors%0A%20%20%20%20%20%20%20referring%20to%20the%20read%20end%20of%20a%20pipe%20have%20been%20closed%2C%20then%20a%0A%20%20%20%20%20%20%20write(2)%20will%20cause%20a%20SIGPIPE%20signal%20to%20be%20generated%20for%20the%0A%20%20%20%20%20%20%20calling%20process.%20%20If%20the%20calling%20process%20is%20ignoring%20this%20signal%2C%0A%20%20%20%20%20%20%20then%20write(2)%20fails%20with%20the%20error%20EPIPE.):
  > If all file descriptors referring to the read end of a pipe have been closed, then a [write(2)](https://man7.org/linux/man-pages/man2/write.2.html) will cause a SIGPIPE signal to be generated for the calling process. If the calling process is ignoring this signal, then [write(2)](https://man7.org/linux/man-pages/man2/write.2.html) fails with the error EPIPE.
- So normally, `yes` is terminated by `SIGPIPE` with no error output (before `write` returns) when the reader closes the pipe.
- But with scubainit ignoring `SIGPIPE` (due to Rust startup code), and `yes` inheriting it, `yes` instead sees `write` return with `EPIPE`, resulting in an error message before termination.

Please correct me if I got any of that wrong.

**Comment by JonathonReinhart** [comment]
`demo.sh`:
```bash
#!/bin/bash
vers=(2.12.0 2.13.0)
for ver in ${vers[@]}; do
    echo "======== Scuba ${ver} ========"
    venv="scuba-${ver}"
    python3 -m venv $venv || exit $?
    ${venv}/bin/pip install "scuba==${ver}" || exit $?
    ${venv}/bin/scuba --version
    ${venv}/bin/scuba --image debian:12 sh -c "yes | echo abcd"
done
```

Output:
```console
$ ./demo.sh
======== Scuba 2.12.0 ========
Requirement already satisfied: scuba==2.12.0 in ./scuba-2.12.0/lib/python3.11/site-packages (2.12.0)
Requirement already satisfied: PyYAML in ./scuba-2.12.0/lib/python3.11/site-packages (from scuba==2.12.0) (6.0.1)
scuba 2.12.0
abcd
======== Scuba 2.13.0 ========
Requirement already satisfied: scuba==2.13.0 in ./scuba-2.13.0/lib/python3.11/site-packages (2.13.0)
Requirement already satisfied: PyYAML in ./scuba-2.13.0/lib/python3.11/site-packages (from scuba==2.13.0) (6.0.1)
scuba 2.13.0
abcd
yes: standard output: Broken pipe
```

This matches the problem described above.

As does this:
```console
$ strace -o yes.strace yes | echo abcd
```

`yes.strace`:
```strace
...
write(1, "y\ny\ny\ny\ny\ny\ny\ny\ny\ny\ny\ny\ny\ny\ny\ny\n"..., 8192) = -1 EPIPE (Broken pipe)
--- SIGPIPE {si_signo=SIGPIPE, si_code=SI_USER, si_pid=693228, si_uid=1000} ---
+++ killed by SIGPIPE +++
```
